version: '3'

vars:
  # K3d configuration
  K3D_CLUSTER_NAME: testcluster
  LOCAL_IMAGE_REGISTRY_URI: localregistry.localhost
  LOCAL_IMAGE_REGISTRY_PORT: 12345

  APP_NAME: role-controller

tasks:
  default:
    cmds:
      - task help
    silent: true

  help:
    cmds:
      - echo "Welcome to my project - maintainer<Tommy Tran Duc Thang> - email<tommytran.dev@gmail.com>"
      - echo ""
      - echo "Run task <task_name> to run predefined script"
      - echo "For local development         Flow will be local:install -> local:bootstrap -> local:dev -> local:clean"
      - echo "For local ci test             Run task local:ci"
      - echo "For ci                        Run task ci:execute"
      - echo ""
      - task -l
    silent: true

  local:install:
    desc: install dependancies for macOS and Ubuntu
    cmds:
      - command -v devbox &> /dev/null || { curl -fsSL https://get.jetify.com/devbox | bash; }
      - devbox install 
    silent: true

  local:bootstrap:
    desc: setup k3d cluster for dev environment
    cmds:
      - k3d registry create {{.LOCAL_IMAGE_REGISTRY_URI}} --port {{.LOCAL_IMAGE_REGISTRY_PORT}}
      - k3d cluster create {{.K3D_CLUSTER_NAME}} --registry-use k3d-{{.LOCAL_IMAGE_REGISTRY_URI}}:{{.LOCAL_IMAGE_REGISTRY_PORT}}

  local:dev:
    desc: Setup the application in the local cluster and enable hot reloading for development
    cmds:
      - tilt up

  local:clean:
    desc: clean up all resources
    cmds:
      - tilt down
      - k3d cluster delete {{.K3D_CLUSTER_NAME}}
      - k3d registry delete {{.LOCAL_IMAGE_REGISTRY_URI}}

  local:test:
    desc: Running test
    cmds:
      - go test ./...
    silent: true

  ci:execute:
    desc: Execute CI (Pipeline Only)
    cmds:
      - earthly +ci --IMAGE_NAME={{.APP_NAME}} --TAG={{.SHA}}
    vars:
      SHA:
        sh: git rev-parse HEAD
    silent: true

  kiki:
    desc: (Easter Egg)
    cmds:
      - echo "I love you my kiki Dayeon :3"
    silent: true
