version: '3'

vars:
  K3D_CLUSTER_NAME: testcluster
  LOCAL_IMAGE_REGISTRY_URI: localregistry.localhost
  LOCAL_IMAGE_REGISTRY_PORT: 12345

tasks:
  install:
    desc: install dependancies for macOS and Ubuntu
    cmds:
      - command -v tilt &> /dev/null || curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh
      - command -v k3d &> /dev/null || curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - |
        command -v helm &> /dev/null || { curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
        chmod 700 get_helm.sh && \
        ./get_helm.sh; }
      - command -v go &> /dev/null || { echo "Go is required. Please install Go"; exit 1; }
      - command -v docker &> /dev/null || { echo "Docker is required. Please install Docker"; exit 1; }

  bootstrap:
    desc: setup k3d cluster
    cmds:
      - k3d registry create {{.LOCAL_IMAGE_REGISTRY_URI}} --port {{.LOCAL_IMAGE_REGISTRY_PORT}}
      - k3d cluster create {{.K3D_CLUSTER_NAME}} --registry-use k3d-{{.LOCAL_IMAGE_REGISTRY_URI}}:{{.LOCAL_IMAGE_REGISTRY_PORT}}
  dev:
    desc: running
    cmds:
      - tilt up
  clean:
    desc: clean up all resources
    cmds:
      - tilt down
      - k3d cluster delete {{.K3D_CLUSTER_NAME}}
      - k3d registry delete {{.LOCAL_IMAGE_REGISTRY_URI}}
