apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-sa-crud-secret-binding
subjects:
- kind: ServiceAccount
  name: cloud-role-identity-controller-service-account 
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: read-sa-crud-secret
  apiGroup: rbac.authorization.k8s.io
