# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "sample-example"
  namespace: default
spec:
  serviceAccountName: sample-service-account
  containers:
  - name: sample-example
    image: "nginx:latest"
    ports:
    - containerPort: 80
      name: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-service-account
  namespace: default
  annotations:
    ENABLE_PROVIDER_ROLE: "aws"
    AWS_ROLE_ARN: "arn-sample" 
